---
# Set here which repository you want to use for the deployments
# public: repo.keedio.com
# local: Local VM Buildoop 
repo_address: 'public'
#
# set the development variable to true if you are a Keedio developer 
development: false  
#
# includes 32 bits development support (only for fw1-loggrabber)
development_32bits: false 
#
# Specify here the deployment type
# ambari: an ambari cluster will be installed
# standalone: independent VMs ready for manual installation
deployment: ambari
#
# Enable here free IPA installation
# which includes LDAP and Kerberos
# Important if you want your cluster securized 
ipa: false 
#  
# Specify the name resolution method
# static: A precompiled file is copied in /etc/hosts (Default for Virtualbox)
# aws: The post-installation script aws_hosts (Default for AWS)
# azure: The post-installation script az_hosts needs to be manually executed (Default for Azure)
nameresolution: 'aws'

#
# Specify the ambary backend database
# default: the default db shipped with ambari (postgres) 
# mysql: mysql running on the master,  requires manual configuration
ambaridb: 'default' 

# set master here for multiclustering
set_master: 'kdsmaster'
